#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:restIndex }

products_top:
    path:     /products/by-top/{limit}/{prodcatId}
    defaults: { _controller: AppBundle:Products:top, limit: 20, prodcatId: 0 }
    requirements:
        limit:  10|20|30
        prodcatId:  \d+
        methods: GET

products_by_id:
    path:     /products/details/{prodId}
    defaults: { _controller: AppBundle:Products:details}
    requirements:
        prodId:  \d+
        methods: GET

