#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Default:restIndex }

products_top:
    path:     /products/by-top/{limit}
    defaults: { _controller: AppBundle:Products:top, limit: 20 }
    requirements:
        limit:  10|20|30
        methods: GET

products_by_id:
    path:     /products/by-id/{id}
    defaults: { _controller: AppBundle:Products:cached, id:1 }
    requirements:
        c:  \d+   

