# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    apromo_cache:
            class: Doctrine\Common\Cache\PhpFileCache
            arguments: [%kernel.cache_dir%]
    response_factory:
        class: AppBundle\Utils\ResponseFactory
        arguments: [%response_cfg.cache_time%,%response_cfg.json_params%]
    common_data:
        class: AppBundle\Utils\CommonData
        arguments: ["@doctrine"]
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }